#! /bin/bash      just for vscode highlighting

# Sidebar binds
bind index G imap-fetch-mail

bind index,pager <C-UP> sidebar-prev                  # Ctrl-up to select next folder
bind index,pager <C-DOWN> sidebar-next                # Ctrl-down to select previous folder
bind index,pager <C-RIGHT> sidebar-open               # Ctrl-right to open selected folder
bind index,pager <C-LEFT> sidebar-toggle-visible      # Ctrl-left to toggle visibility of the sidebar

macro index,pager <S-UP>    "<previous-entry><tag-message><previous-entry>"   # Shift-up to toggle tagging message upwardly
macro index,pager <S-DOWN>  "<tag-message>"                                   # Shift-down to toggle tagging message downwardly
macro index,pager <S-LEFT>  "<untag-pattern>~A<enter>"                        # Shift-left to untag all messages


macro index b '<enter-command>toggle sidebar_visible<enter><refresh>'
macro pager b '<enter-command>toggle sidebar_visible<enter><redraw-screen>'

macro pager I <set-flag>N "mark as unread"
macro index I "<tag-prefix><set-flag>N" "mark as unread"
macro pager i <clear-flag>N "mark as read"
macro index i "<tag-prefix><clear-flag>N" "mark as read"

# The following macro binds k to filter messages by sender
# make note about the special variable my_tmp_pipe_decode it's predefined and you can't use an arbitrary variable
# Refer to the following question: https://unix.stackexchange.com/a/510349/114816
macro index,pager k "<pipe-message>formail -X from:|awk -F'[<>]' '{print \"set my_tmp_pipe_decode=\\\"\"$2\"\\\"\" }'>/tmp/sender<enter>:source /tmp/sender<enter>l~f $my_tmp_pipe_decode<enter>" "Filter Messages Like"

macro pager <S-HOME>       "q<first-entry><enter>"
macro pager <S-END>        "q<last-entry><enter>"
macro pager <S-Prev>       "<previous-page>"
macro pager <S-Next>       "<next-page>"

# [m]ove a mail to another folder (in Gmail, "m" would be "[m]ute").
# macro pager m "<save-message>?<toggle-mailboxes>" "move to..."
# macro index m "<tag-prefix><save-message>?<toggle-mailboxes>" "move to..."

# bind pager <down> next-line
# bind pager <up> previous-line
#
# macro index y '<change-folder>?<toggle-mailboxes>
# macro pager \cU 'urlview' 'Follow links with urlview'

# #-------~---~----------~----------~----
# # Key bindings
# #-------~---~----------~----------~----
bind index r group-reply
# bind index g first-entry
# bind index G last-entry
# bind index N search-opposite
# bind index o collapse-thread
# bind index O collapse-all
# bind index R toggle-new
# bind index \# sync-mailbox
# #-------~---~----------~----------~----
# #-------~---~----------~----------~----
# bind attach g first-entry
# bind attach G last-entry
# # use a graphical browser configured via mailcap like so:
# #  # bound as <return> on attachments view in mutt
# #  text/html;xdg-open...
# #  # default command for mutt to use when viewing html emails w/ no text version
# #  text/html;w3m...
# bind attach <return> view-mailcap
# # default saving of attachments to ~/downloads
# macro attach s <save-entry><bol>~/downloads/<eol>
# #-------~---~----------~----------~----
# bind pager g top
# bind pager G bottom
# #-------~---~----------~----------~----
# bind attach,index,pager \CD next-page
# bind attach,index,pager \CU previous-page
#
#
#


# use tab to complete address.
# bind editor <Tab> complete-query
bind editor ^T complete

bind index N search-opposite
bind pager N search-opposite

macro index,pager L "lall\n"

# macro index,browser .r "<enter-command>source ~/.muttrc<enter>"


# ----------------------------
# Script section:
# ----------------------------
bind pager \\ noop
macro index,pager ",u" "<enter-command>set pipe_decode = yes<enter><pipe-message>urlview<enter><enter-command>set pipe_decode = no<enter>" "view URLs"
# inorder for this to work you need to install 'libmime-tools-perl'
macro index,pager,compose <RIGHT> '<pipe-entry>~/bini3/,mail-decoder -v --select=best<enter>' # Use right arrow to view html

macro index,pager,compose <S-RIGHT> '<pipe-entry>~/bini3/,mail-decoder -v -a 1 --select=best<enter>' # Use Shift+right arrow to view html with netsurf
macro index,pager,compose <A-RIGHT> '<pipe-entry>~/bini3/,mail-decoder -v -a 2 --select=best<enter>' # Use Alt+right arrow to view html with chrome

macro index,pager ",m" ":unset wait_key\n |~/.mutt/scripts/add_to_calcurse<enter><exit>"
# See more flags at https://man.cx/pandoc or http://pandoc.org/MANUAL.html
macro compose \e5 "F pandoc --css $HOME/.mutt/github.css --standalone --self-contained  -s -f gfm+line_blocks+hard_line_breaks -t html --quiet \ny^T^Utext/html; charset=us-ascii\n"

set display_filter      = "$HOME/.mutt/scripts/alias-manager.py  --file=$HOME/.mutt/alias.key -p"

# -----------------------------
# -----------------------------



macro index,pager <f1> '<sync-mailbox><enter-command>unmailboxes *<enter><enter-command>source ~/.mutt/account.gmail<enter><change-folder>!<enter><redraw-screen>'
macro index,pager <f2> '<sync-mailbox><enter-command>unmailboxes *<enter><enter-command>source ~/.mutt/account.axis<enter><change-folder>!<enter><redraw-screen>'



# navigation/saving ---------------------------------------------------
bind index,pager            w   sync-mailbox # default is $, but this is more like vim 'write'
macro index,pager           W   "<sync-mailbox><shell-escape>mailsync<enter>" "Sync mailbox and offlineimap." #<shell-escape>
macro index,pager           $   "<sync-mailbox><shell-escape>mailsync -V $title<enter>" "run mbsync to sync $title"
bind index,pager            ZZ  quit # save changes to mailbox and quit
bind pager                  q   exit # exit back to index
bind index                  q   noop # remove q binding
bind index                  qq  exit # exit mutt without syncing changes
#bind generic,pager,browser,attach,compose,pgp,smime,postpone,query <esc> exit

# vim: fdm=marker
# vim: filetype=muttrc
