#! /bin/bash      just for vscode highlighting

# https://github.com/tomauty/dotfiles/blob/master/mutt/.mutt/muttrc
# https://github.com/ervandew/dotfiles/blob/master/.muttrc
set use_from=yes
set mail_check_stats

# +/^s searches and jumps to the first empty line; ++1 goes one line further then 'noh' removes syntax highlighting
set editor = 'vim +/^$ ++1 -c "noh" -c "set spell spelllang=en" -c "set textwidth=72" -c "set wrap"'

# set editor="emacs -geometry 90x73+298+0"
set edit_headers


set record = ''
set mbox_type = Maildir

#--------------------------------------
# Mail options
#-------~---~----------~----------~----
set confirmappend = no                 # don't prompt when moving a message to another folder.
set edit_headers                       # allow editing headers when composing mail.
set include = yes
set mime_forward = yes                   # when forwarding, include attachments
set mime_forward_rest = yes
set send_charset      = 'us-ascii:utf-8'
set smart_wrap

set move = no                          # By default, Mutt will ask you to move read messages from INBOX to another mailbox (set by mbox)
set recall=no                          # Prevent Mutt from asking me to recall a postponed message when composing
set delete                             # Don't ask for comfirmation to append a message to an existing mailbox
set fast_reply                         # don't prompt for forward subject or to/subject on reply
set noprompt_after

# set up the pager (use vim)
# set pager="vim -nc 'setlocal readonly ignorecase ft=mail' -c 'nmap q :q!<CR>'"
# set pager="w3m -o auto_image=TRUE "
# set pager="elinks -dump"
# set pager="cat %s|pipe2w3m.sh"
# set pager_format="-%S- %-20.20f %s"

set pager_stop
set pager_context=3
set pager_index_lines=20               # Split the view and show pager at line 20

ignore "Authentication-Results:"
ignore "DomainKey-Signature:"
ignore "DKIM-Signature:"

# %<[y?%<[m?%<[d?%[%H:%M ]&%[%a %d]>&%[%b %d]>&%[%m/%y ]>
# %<[y?                                       &%[%m/%y ]>  Older
#      %<[m?                        &%[%b %d]>             This year
#           %<[d?         &%[%a %d]>                       This month
#                %[%H:%M ]                                 Today
#
set index_format="%3C %zs %?X?A& ? %<[m?%<[d?%[ %H:%M:%S]&%[%a %m-%d]>&%[%y-%m-%d ]> %-20.20F %s (%-4.4c)"
# --------------------------------                   Date portion                    --------------------"
# -------------------------------- %<[m?%<[d?%[ %H:%M:%S]&%[%a %m-%d]>&%[%y-%m-%d ]> --------------------"

set status_chars  = " *%A"

set status_format = "─┤   %-20f ├─┤%r%m messages%?n? (%n new  )?%?d? (  %d to delete )?%?t? (  %t tagged)? ├───%>─%?p?┤  %p postponed ├?───"
# set status_format= "-%r-Personal: %f [Msgs:%?M?%M/?%m%?n? New:%n?%?o? Old:%o?%?d? Del:%d?%?F? Flag:%F?%?t? Tag:%t?%?p? Post:%p?%?b? Inc:%b?%?l? %l?]---(%s/%S)-%>-(%P)---\n"

set status_on_top


set sort             = "threads"
set strict_threads   = "yes"
set sort_aux         = "reverse-last-date-received"
set sort_browser     = "reverse-date"
set sort_re             # thread based on regex
set reply_regexp = "^(([Rr][Ee]?(\[[0-9]+\])?: *)?(\[[^]]+\] *)?)*"
unset uncollapse_jump
unset collapse_unread
set collapse_all = no
set uncollapse_new = yes


#-------~---~----------~----------~----
# Sidebar Config
#-------~---~----------~----------~----
set sidebar_width         = 30
set sidebar_visible       = yes
set sidebar_format = '%B%?F? [%F]?%* %?N?%N/? %?S?%S?'

#-------~---~----------~----------~----
# Various Settings
#-------~---~----------~----------~----
#
# set followup_to       = "yes"
# unset metoo

set beep_new
set sleep_time = 0
set wait_key          = "no"           # Don't ask press enter to continue on external viewers
set nomark_old                         # Don't mark messages old
auto_view text/html
alternative_order text/html text/enriched text/plain


set certificate_file="~/.mutt/certificates"
set message_cachedir="~/.mutt/cache/bodies"
set header_cache="~/.mutt/cache/headers"


#-------~---~----------~----------~----
# Browsing / Composing
#-------~---~----------~----------~----
set charset = "utf-8"
set signature="echo Reza|"

# set display_filter="sed -e '/^\[-- Autoview using \.\j* --\]$/d'"

#-------~---~----------~----------~----
# IMAP Settings
#-------~---~----------~----------~----
# set imap_keepalive = 300
# set mail_check     = 20
# set imap_check_subscribed

set query_command="lbdbq '%s'"            # Use the little brother database for doing queries. `sudo apt install lbdb`

set text_flowed=yes
set mailcap_path 	= ~/.mutt/.mailcap


#-------~---~----------~----------~----
# Sourcing
#-------~---~----------~----------~----

source ~/.mutt/folder-hooks
source ~/.mutt/alias_g.key
source ~/.mutt/alias_a.key
# source ~/.mutt/schemes/vombatidae.muttrc
source ~/.mutt/schemes/reza.muttrc
# source ~/.mutt/schemes/lukesmith.muttrc
source ~/.mutt/auto_views
source ~/.mutt/bindings
source ~/.mutt/account.$DEFAULT_MAIL
#source ~/.mutt/account.axis



#-------~---~----------~----------~----
# Hooks
#-------~---~----------~----------~----
folder-hook . exec collapse-all
folder-hook . 'exec first-entry'


# vim: fdm=marker
# vim: filetype=muttrc
