#!/bin/zsh

[ -f /usr/share/applications/$2.desktop ] ||
{
echo "${bW}Usage:${cZ} ,create-shortcut <executable-file> <name>"
sudo sh -c "cat >> /usr/share/applications/$2.desktop << EOF
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=$1
Name=$2
Comment=comment here
Icon=$1.icon
EOF"
}

echo "${bW}File:${cZ} /usr/share/applications/$2.desktop"
sudo gnome-desktop-item-edit /usr/share/applications/$2.desktop
