#!/bin/zsh
key_layout_msg="<span font_variant='smallcaps' font='ProFontIIx Nerd Font Book 50' foreground='#eeeeee'>$(xkb-switch | cut -c1-2)<b><span foreground='#bbbbbb' font='40'> </span></b></span>"
key_icon=$HOME/bini3/ext-icons/kb-4.png

exec dunstify -app lang "keyboard layout changed:" $key_layout_msg -i $key_icon -r 10001

