#!/bin/zsh
current_lang=$(xkb-switch -p)
key_layout_msg="<span font_variant='smallcaps' font='ProFontIIx Nerd Font Book 50' foreground='#eeeeee'>"
key_layout_msg+=" $current_lang"
key_layout_msg+="<b>"
key_layout_msg+="<span foreground='#bbbbbb' font='40'> "
key_layout_msg+="</span>"
key_layout_msg+="</b>"
key_layout_msg+="</span>"

# key_icon=$HOME/bini3/ext-icons/kb.png
key_icon=$HOME/bini3/ext-icons/$current_lang.png

exec dunstify -app lang "Current layout:" $key_layout_msg -i $key_icon -r 10001

