#!/bin/zsh

# You can call this script like this:
# $./volume.sh up
# $./volume.sh down
# $./volume.sh mute

function get_volume {
    amixer -D pulse get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
    amixer -D pulse get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

#Repeat char n times
function rchar {
   print "${$(printf "%$1s" "")// /$2}"
}

function send_notification {
   volume=`get_volume`
    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character
    # bar=$(seq -s "█" $(($volume / 5)) | sed 's/[0-9]//g')
    # barrest=$(seq -s "░" $((100 / 5 - $volume / 5)) | sed 's/[0-9]//g')
    bar=$(rchar $(($volume / 5)) "█")
    barrest=$(rchar $((20 - $volume / 5)) "░")
    case $(($volume)) in
       (0)              s="muted";; # 0
       ([0-9]|[1][0-9]) s="low";; # <20
       ([2-3][0-9])     s="low";; # 20>=x>40
       ([4-5][0-9])     s="medium";; # 40>=x>60
       ([6-7][0-9])     s="medium";; # 60>=x>80
       ([8-9][0-9])     s="high";; # 80>=x>100
       (100)            s="muted-blocking";; # 100
    esac
    # Send the notification
    dunstify -i "av-$s" -r 2593 -u normal "$(printf "$bar$barrest [%03d]" $volume)" -a volume
}

# flog ,volume "$1"
case $1 in
   notify)
      send_notification
   ;;
   up)
      # Set the volume on (if it was muted)
      amixer -D pulse set Master on > /dev/null
      # Up the volume (+ 5%)
      amixer -D pulse sset Master 10%+ > /dev/null
      send_notification
	;;
   down)
      amixer -D pulse set Master on > /dev/null
      amixer -D pulse sset Master 10%- > /dev/null
      send_notification
	;;
   mute)
      send_notification
    	# Toggle mute
      amixer -D pulse set Master 1+ toggle > /dev/null
      if is_mute ; then
          dunstify -i audio-volume-muted -t 8 -r 2593 -u normal "Mute"
      else
          send_notification
      fi
	;;
esac
echo `get_volume`

pkill -SIGRTMIN+11 i3blocks
