#!/bin/bash -e
sudo chown "$USER" "/tmp/i3exit.log"

action="$1"

# if called without an argument, generate menu
if [ -z "$action" ]; then
    actions=("<span color='#DACFAA'>  </span> Lock screen"         "lock"
             "<span color='#C28A1E'>  </span> Suspend computer"    "suspend"
             "<span color='#5E8E60'>  </span> Exit window manager" "logout"
             "<span color='#B8201A'>  </span> Reboot system"       "reboot"
             "<span color='#d61c27'>  </span> Power-off system"    "shutdown")
    printf -v menu "%s <small>(%s)</small>\n" "${actions[@]}"
    menu="${menu%%[[:space:]]}"
    index=$(echo -e "${menu}" |
                rofi -dmenu -i -markup-rows \
                     -no-custom -p "Action: " -format i)
    action="${actions[$((index * 2 + 1))]}"
fi
dunstify "i3-dexit called with [$action] Home is [$HOME]"
case "$action" in
    lock)
        i3exit $HOME/bini3/lock 
        ;;
    logout)
        i3exit $HOME/bini3/logout 
        ;;
    reboot)
        sudo $HOME/bini3/i3exit reboot 
        ;;
    suspend)
        sudo $HOME/bini3/i3exit suspend 
        ;;
    shutdown)
        sudo $HOME/bini3/i3exit shutdown 
        ;;
    *)
        echo "Usage: $0 (lock|suspend|logout|reboot|shutdown)"
        exit 1
esac
