#!/bin/zsh

# RES=$(xdpyinfo | grep dimensions | awk '{print $2}')
# WALL_PATH="$HOME/Pictures/wallpapers"
# WALL=$(find $WALL_PATH -iname '*.*'| shuf -n 1)
# convert -scale $RES $WALL /tmp/lock.png
# i3lock -i /tmp/lock.png -f -p default

# to cache images with better lockscreen use the following command:
# ~/bini3/betterlockscreen -u ~/Pictures/wallpapers
$HOME/bini3/betterlockscreen -l
$HOME/bini3/betterlockscreen -u ~/Pictures/wallpapers
