#!/usr/bin/python
# 
# Thanks 2 [Maxim](https://askubuntu.com/users/269589/maxim)
# Script for catching mouse input without changing the event
# pip3.6 install PyUserInput
# pip install tendo
from pymouse import PyMouseEvent
from pykeyboard import PyKeyboard
import os
from tendo import singleton
me = singleton.SingleInstance() # will sys.exit(-1) if other instance is running

k = PyKeyboard()
class MouseToButton(PyMouseEvent):
    def click(self, x, y, button, press):
        # if button == 8:
        #     if press:    # press
        #         k.press_key(k.control_l_key)
        #     else:        # release
        #         k.release_key(k.control_l_key)
        if button == 1:
            if press:
                os.system("pn click")
            # print("reza",button,press)

C = MouseToButton()
C.run()
