#!/bin/zsh
if [ -z $@ ]
then
function gen_workspaces()
{
    i3-msg -t get_workspaces | tr ',' '\n' | grep "name" | sed 's/"name":"\(.*\)"/\1/g' | sort -n
}

echo empty; gen_workspaces
else
   WORKSPACE=$@
   if [ x"empty" = x"${WORKSPACE}" ]
   then
       ~/bin/i3-empty-ws > /dev/null
   elif [ -n "${WORKSPACE}" ]
   then
       i3-msg workspace "${WORKSPACE}" > /dev/null
   fi
fi
exit 0
