#!/bin/bash

wid=$1
mod=$2

if [[ $mod == "new" ]]; then
  CURRENT_TITLE=$(~/bini3/i3-get-best-guess-title "$wid")
  echo "$CURRENT_TITLE"
  if [[ $CURRENT_TITLE == "OI::"* ]]; then
    # Replace OI:: and append %title to have dynamic titles
    CURRENT_TITLE="${CURRENT_TITLE//OI\:\:/}%title"
  fi
  i3-msg "[id=$wid] focus; title_format $CURRENT_TITLE"
  echo "$CURRENT_TITLE"
elif [[ $mod == "focus" ]]; then
  class=$(xprop -id "$wid" WM_CLASS | cut -d\" -f4)
  TITLE=$(xprop -id "$wid" _NET_WM_VISIBLE_NAME | cut -d\" -f2)
  # notify-send "$class:$TITLE" "$mod $CURRENT_LANG" 
  case "$class" in
    # Gedit|TelegramDesktop)
    #   CURRENT_LANG=$(xkb-switch | cut -c1-2)
    #   xkb-switch -s ir
    #   ;;
    # "Org.gnome.gedit")
    #   xkb-switch -s ir
    #   ;;
    *)
      # If the class is not important switch based on the title
      case "$TITLE" in
      *PLS*)
        CURRENT_LANG=$(xkb-switch | cut -c1-2)
        xkb-switch -s ir
        ;;
      *)
        xkb-switch -s us
        ;;
      esac
      ;;
  esac
fi
