#!/bin/bash
# This is just a wrapper around msmtp to provide thunneling

ssh -q -f -N -M -S /tmp/ssh_tunnel_%h.sock -o ExitOnForwardFailure=yes -L 1358:xmail.axis.com:25  LNAX
# ssh -f -M -L 1358:xmail.axis.com:25  LNAX sleep 10;
msmtp $@
ssh -S /tmp/ssh_tunnel_%h.sock -O exit LNAX

